image: .

stages:
  - setup
  - build
  - test

# Execute only for merge-requests, commits to default branch, and tags.
include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

composer-install:
  stage: setup
  before_script:
    - ./bin/composer config -g cache-dir "$CI_PROJECT_DIR/.cache/composer/"
  script:
    - ./bin/composer install --no-progress
  cache:
    key:
      files:
        - composer.lock
    paths:
      - .cache/composer/
  artifacts:
    expire_in: 1h
    paths:
      - vendor/

validate-composer:
  stage: test
  script:
    - ./bin/composer validate --strict
  dependencies: []

phpcs:
  stage: test
  script:
    - ./vendor/bin/phpcs

php-cs-fixer:
  stage: test
  script:
    - ./vendor/bin/php-cs-fixer fix -v --dry-run

composer-unused:
  stage: test
  script:
    - ./bin/composer unused

composer-require-checker:
  stage: test
  script:
    - ./vendor/bin/composer-require-checker check --config-file composer-require-checker-config.json

phpstan:
  stage: test
  script:
    - ./vendor/bin/phpstan analyse --memory-limit=-1

phpunit:
  stage: test
  before_script:
    - yum -y install --setopt=tsflags=nodocs php-xdebug
  script:
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --colors=never
    - php coverage-checker.php build/coverage-report/clover.xml 91
  artifacts:
    reports:
      cobertura: build/coverage-report/cobertura.xml
